In [0]:
# Change directory to VSCode workspace root so that relative path loads work correctly. Turn this addition off with the DataScience.changeDirOnImportExport setting
import os
try:
	os.chdir(os.path.join(os.getcwd(), 'PytonLessons/PyForDS'))
	print(os.getcwd())
except:
	pass


In [1]:
import numpy as np

a = np.arange(12,24,1,dtype = int)
a


array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [2]:
a1= a.reshape((2, 6)).copy()
a1


array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [3]:
a2= a.reshape((3, 4))
a2


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [4]:
a3= a.reshape((4, 3))
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [5]:
a4= a.reshape((6, 2))
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [6]:
a5= np.dot(a4, a1)
a5




array([[378, 403, 428, 453, 478, 503],
       [438, 467, 496, 525, 554, 583],
       [498, 531, 564, 597, 630, 663],
       [558, 595, 632, 669, 706, 743],
       [618, 659, 700, 741, 782, 823],
       [678, 723, 768, 813, 858, 903]])

In [7]:
a6 = a.reshape(2,-1)
a6

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [8]:
a7 = a.reshape (3,-1)
a7

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [9]:
a8=a.reshape(-1, 2)
a8

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [10]:
a9=a.reshape(-1, 3)
a9

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [11]:
a10=a.reshape(-1, 4)
a10

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
print('Да, вектор это одномерный массив')

Да, вектор это одномерный массив


In [13]:
a=np.arange(20, 0, -2)
print (a)
b=[]
for i in range(20,0, -2):
    b.append([i])    
print(b)
print('Если я правильно понял задание(мне кажется что нет), то разница в том что первый массив единичен, второй является массивом массивов столбцов')



[20 18 16 14 12 10  8  6  4  2]
[[20], [18], [16], [14], [12], [10], [8], [6], [4], [2]]
Если я правильно понял задание(мне кажется что нет), то разница в том что первый массив единичен, второй является массивом массивов столбцов


In [14]:
a=np.zeros((5,5), dtype=int)
b=np.ones((4,5))
np.vstack((a,b))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
a=np.arange(0,12)
A=a.reshape(4,3)
At=A.transpose()
B=np.dot(A,At)
print(B)
np.shape(B)
#4/4
np.linalg.det(B)
#определитель равен нулю следовательно обратная матрица невозможна

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


0.0

In [16]:
np.random.seed(42)
A=np.random.randint(0,16,16)
C=A.reshape(4,4)
D=np.add(B,C*10)

In [17]:
np.linalg.det(D)

-28511999.999999944

In [18]:
np.linalg.matrix_rank(D)

4

In [19]:
D_inv=np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

In [20]:

for i in D_inv:
    for j in D_inv[i]:    
        if D_inv[i,j]<0:
            D_inv[i,j]=0
        elif D_inv[i,j]>0:
            D_inv[i,j]=1
    

IndexError: arrays used as indices must be of integer (or boolean) type

In [21]:
#10 
for i in D_inv:
    for j in D_inv[i]:    
        if D_inv[j]<0:
            D_inv[j]=0
        elif D_inv[j]>0:
            D_inv[j]=1
    

IndexError: arrays used as indices must be of integer (or boolean) type

In [22]:
#10 
for i in D_inv:
        if D_inv[i]<0:
            D_inv[i]=0
        elif D_inv[i]>0:
            D_inv[i]=1
    

IndexError: arrays used as indices must be of integer (or boolean) type

In [23]:
#10 
for index, i in D_inv:       
    if i<0:
        D_inv[index]=0
    elif i>0:
        D_inv[index]=1
    

ValueError: too many values to unpack (expected 2)

In [24]:
#10 
for index, i in D_inv:       
    if i<0:
        D_inv[index]=0
    elif i>0:
        D_inv[index]=1
    

ValueError: too many values to unpack (expected 2)

In [25]:
#10 
for index, i in np.ndenumerate(D_inv):       
    if i<0:
        D_inv[index]=0
    elif i>0:
        D_inv[index]=1
    

In [26]:
#10 
for index, i in np.ndenumerate(D_inv):       
    if i<0:
        D_inv[index]=0
    elif i>0:
        D_inv[index]=1
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [27]:
a = np.array[[1,6],[2,8],[3,11],[3,10],[1,7]]
a

TypeError: 'builtin_function_or_method' object is not subscriptable

In [28]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [29]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_a = a.mean(a, int, mean_a)
mean_a

NameError: name 'mean_a' is not defined

In [30]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_a = a.mean(axis=1)
mean_a

array([3.5, 5. , 7. , 6.5, 4. ])

In [31]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

In [32]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_a = a.mean(axis=1)
mean_a

array([3.5, 5. , 7. , 6.5, 4. ])

In [33]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_a = a.mean(axis=2)
mean_a

IndexError: tuple index out of range

In [34]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

In [35]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_a = a.mean(axis=-1)
mean_a

array([3.5, 5. , 7. , 6.5, 4. ])

In [36]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_a = np.mean(a[:,0])
mean_a

2.0

In [37]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_a = np.mean(a[:,1])
mean_a

8.4

In [38]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_a = np.mean(a[:1,1])
mean_a

6.0

In [39]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_a = np.mean(a[0,1])
mean_a

6.0

In [40]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_a = np.mean(a[0,:])
mean_a

3.5

In [41]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_a = np.mean(a[0:1])
mean_a

3.5

In [42]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_b = np.mean(a[:,0])
mean_c=np.mean(a[:,1])
mean_a = np.concatenate(mean_b, mean_c)
mean_a

TypeError: 'numpy.float64' object cannot be interpreted as an integer

In [43]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_b = np.mean(a[:,0])
mean_c=np.mean(a[:,1])
mean_a = np.concatenate(mean_b, mean_c)
mean_a

TypeError: 'numpy.float64' object cannot be interpreted as an integer

In [44]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_b = np.mean(a[:,0])
mean_c=np.mean(a[:,1])
mean_a = np.concatenate((mean_b, mean_c),0)
mean_a

ValueError: zero-dimensional arrays cannot be concatenated

In [45]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_b = np.mean(a[:,0])
mean_c=np.mean(a[:,1])
mean_a = np.concatenate((mean_b, mean_c))
mean_a

ValueError: zero-dimensional arrays cannot be concatenated

In [46]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_b = np.mean(a[:,0])
mean_b
# mean_c=np.mean(a[:,1])
# mean_a = np.concatenate((mean_b, mean_c))
# mean_a

2.0

In [47]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_b = np.mean(a[:,0])
mean_b
mean_c=np.mean(a[:,1])
mean_a = np.concatenate((mean_b, mean_c))
mean_a

ValueError: zero-dimensional arrays cannot be concatenated

In [48]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_b = np.mean(a[:,0])
mean_b
# mean_c=np.mean(a[:,1])
# mean_a = np.concatenate((mean_b, mean_c))
# mean_a

2.0

In [49]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
# mean_b = np.mean(a[:,0])
# mean_b
mean_c=np.mean(a[:,1])
mean_c
# mean_a = np.concatenate((mean_b, mean_c))
# mean_a

8.4

In [50]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_b = np.mean(a[:,0])
mean_b
mean_c=np.mean(a[:,1])
mean_c
mean_a = np.array([mean_b], [mean_c])
mean_a

TypeError: data type not understood

In [51]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_b = np.mean(a[:,0])
mean_b
mean_c=np.mean(a[:,1])
mean_c
mean_a = np.array([[mean_b], [mean_c]])
mean_a

array([[2. ],
       [8.4]])

In [52]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_b = np.mean(a[:,0])
mean_b
mean_c=np.mean(a[:,1])
mean_c
mean_a = np.array([[mean_b], [mean_c]])
mean_a

array([[2. ],
       [8.4]])

In [53]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_b = np.mean(a[:,0])
mean_b
mean_c=np.mean(a[:,1])
mean_c
mean_a = np.array(([mean_b], [mean_c]))
mean_a

array([[2. ],
       [8.4]])

In [54]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_b = np.mean(a[:,0])
mean_b
mean_c=np.mean(a[:,1])
mean_c
mean_a = np.vstack(mean_b, mean_c)
mean_a

TypeError: vstack() takes 1 positional argument but 2 were given

In [55]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_b = np.mean(a[:,0])
mean_b
mean_c=np.mean(a[:,1])
mean_c
mean_a = np.vstack((mean_b, mean_c))
mean_a

array([[2. ],
       [8.4]])

In [56]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_b = np.mean(a[:,0])
mean_b
mean_c=np.mean(a[:,1])
mean_c
mean_a = np.stack((mean_b, mean_c))
mean_a

array([2. , 8.4])

In [57]:

a_centred = a[:,0]-mean_b
a_centred

array([-1.,  0.,  1.,  1., -1.])

In [58]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_b = np.mean(a[:,0])
mean_b
mean_c=np.mean(a[:,1])
mean_c
mean_a = np.stack((mean_b, mean_c))
mean_a


array([2. , 8.4])

In [59]:
#Задание 3
# Вычислите массив a_centered, отняв от значений массива а
# средние значения соответствующих признаков, содержащиеся в массиве mean_a.
# Вычисление должно производиться в одно действие.
# Получившийся массив должен иметь размер 5x2.

In [59]:

a_centred = a[:,0]-mean_b
a_centred

array([-1.,  0.,  1.,  1., -1.])

In [60]:

a_centred = a[:,1]-mean_c
a_centred

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [61]:

a_centred = np.stack((a[:,0]-mean_b, a[:,1]-mean_c ))
a_centred

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

In [62]:

a_centred = np.vstack((a[:,0]-mean_b, a[:,1]-mean_c ))
a_centred

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

In [63]:

a_centred = np.vstack((a[:,0]-mean_b, a[:,1]-mean_c ), -1)
a_centred

TypeError: vstack() takes 1 positional argument but 2 were given

In [64]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_b = np.mean(a[:,0])
mean_b
mean_c=np.mean(a[:,1])
mean_c
mean_a = np.stack((mean_b, mean_c))
mean_a


array([2. , 8.4])

In [65]:
#Задание 3
# Вычислите массив a_centered, отняв от значений массива а
# средние значения соответствующих признаков, содержащиеся в массиве mean_a.
# Вычисление должно производиться в одно действие.
# Получившийся массив должен иметь размер 5x2.

In [65]:

a_centred = np.vstack((a[:,0]-mean_b, a[:,1]-mean_c ))
a_centred

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

In [66]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_b = np.mean(a[:,0])
mean_b
mean_c=np.mean(a[:,1])
mean_c
mean_a = np.stack((mean_b, mean_c))
mean_a


array([2. , 8.4])

In [67]:
#Задание 3
# Вычислите массив a_centered, отняв от значений массива а
# средние значения соответствующих признаков, содержащиеся в массиве mean_a.
# Вычисление должно производиться в одно действие.
# Получившийся массив должен иметь размер 5x2.

In [67]:

a_centred = np.column_stack((a[:,0]-mean_b, a[:,1]-mean_c ))
a_centred

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [68]:

a_centred = np.column_stack((a[:,0]-mean_b, a[:,1]-mean_c ))
a_centred

#Задание 4
# Найдите скалярное произведение столбцов массива a_centered.
# В результате должна получиться величина a_centered_sp.
# Затем поделите a_centered_sp на N-1, где N - число наблюдений.

t = np.dot((a[:,0], a[:,1]))
t

TypeError: matrixproduct() missing required argument 'b' (pos 2)

In [69]:

a_centred = np.column_stack((a[:,0]-mean_b, a[:,1]-mean_c ))
a_centred

#Задание 4
# Найдите скалярное произведение столбцов массива a_centered.
# В результате должна получиться величина a_centered_sp.
# Затем поделите a_centered_sp на N-1, где N - число наблюдений.

t = np.dot(a[:,0], a[:,1])
t

92

In [70]:

a_centred = np.column_stack((a[:,0]-mean_b, a[:,1]-mean_c ))
a_centred

#Задание 4
# Найдите скалярное произведение столбцов массива a_centered.
# В результате должна получиться величина a_centered_sp.
# Затем поделите a_centered_sp на N-1, где N - число наблюдений.

t = np.dot(a[:,0], a[:,2])
t

IndexError: index 2 is out of bounds for axis 1 with size 2

In [71]:

a_centred = np.column_stack((a[:,0]-mean_b, a[:,1]-mean_c ))
a_centred

#Задание 4
# Найдите скалярное произведение столбцов массива a_centered.
# В результате должна получиться величина a_centered_sp.
# Затем поделите a_centered_sp на N-1, где N - число наблюдений.

t = np.dot(a[:,0], a[:,1])
t

92

In [72]:
a_centered_sp/np.size(a_centred)

NameError: name 'a_centered_sp' is not defined

In [73]:
a_centered_sp/np.ndarray.size(a_centred)

NameError: name 'a_centered_sp' is not defined

In [74]:
ans = a_centered_sp/(np.ndarray.size(a_centred)-1)
ans

NameError: name 'a_centered_sp' is not defined

In [75]:
arraysize = np.ndarray.size(a_centred)-1
# ans = a_centered_sp/(np.ndarray.size(a_centred)-1)
arraysize

TypeError: 'getset_descriptor' object is not callable

In [76]:

a_centred = np.column_stack((a[:,0]-mean_b, a[:,1]-mean_c ))
a_centred

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [77]:
#Задание 4
# Найдите скалярное произведение столбцов массива a_centered.
# В результате должна получиться величина a_centered_sp.
# Затем поделите a_centered_sp на N-1, где N - число наблюдений.

a_centered_sp = np.dot(a[:,0], a[:,1])
a_centered_sp

92

In [78]:
arraysize = np.ndarray.size(a_centred)-1
# ans = a_centered_sp/(np.ndarray.size(a_centred)-1)
arraysize

TypeError: 'getset_descriptor' object is not callable

In [79]:
arraysize = (np.ndarray.size(a_centred))-1
# ans = a_centered_sp/(np.ndarray.size(a_centred)-1)
arraysize

TypeError: 'getset_descriptor' object is not callable

In [80]:
arraysize = (np.size(a_centred))-1
# ans = a_centered_sp/(np.ndarray.size(a_centred)-1)
arraysize

9

In [81]:
arraysize = a_centered_sp/(np.size(a_centred))-1
arraysize

8.2

In [82]:
#Задание 4
# Найдите скалярное произведение столбцов массива a_centered.
# В результате должна получиться величина a_centered_sp.
# Затем поделите a_centered_sp на N-1, где N - число наблюдений.

a_centered_sp = np.dot(a[:,0], a[:,1])
a_centered_sp

92

In [83]:
arraysize = a_centered_sp/(np.size(a_centred))-1
arraysize



8.2