In [0]:
# Change directory to VSCode workspace root so that relative path loads work correctly. Turn this addition off with the DataScience.changeDirOnImportExport setting
import os
try:
	os.chdir(os.path.join(os.getcwd(), 'Documents/P_F_DS_GB'))
	print(os.getcwd())
except:
	pass


In [52]:
import numpy as np

a = np.arange(12,24,1,dtype = int)
a


array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [53]:
a1= a.reshape((2, 6)).copy()
a1


array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [54]:
a2= a.reshape((3, 4))
a2


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [55]:
a3= a.reshape((4, 3))
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [56]:
a4= a.reshape((6, 2))
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [57]:
a5= np.dot(a4, a1)
a5




array([[378, 403, 428, 453, 478, 503],
       [438, 467, 496, 525, 554, 583],
       [498, 531, 564, 597, 630, 663],
       [558, 595, 632, 669, 706, 743],
       [618, 659, 700, 741, 782, 823],
       [678, 723, 768, 813, 858, 903]])

In [58]:
a6 = a.reshape(2,-1)
a6

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [59]:
a7 = a.reshape (3,-1)
a7

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [60]:
a8=a.reshape(-1, 2)
a8

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [61]:
a9=a.reshape(-1, 3)
a9

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [62]:
a10=a.reshape(-1, 4)
a10

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [63]:
print('Да, вектор это одномерный массив')

Да, вектор это одномерный массив


In [64]:
a=np.arange(20, 0, -2)
print (a)
b=[]
for i in range(20,0, -2):
    b.append([i])    
print(b)
print('Если я правильно понял задание(мне кажется что нет), то разница в том что первый массив единичен, второй является массивом массивов столбцов')



[20 18 16 14 12 10  8  6  4  2]
[[20], [18], [16], [14], [12], [10], [8], [6], [4], [2]]
Если я правильно понял задание(мне кажется что нет), то разница в том что первый массив единичен, второй является массивом массивов столбцов


In [65]:
a=np.zeros((5,5), dtype=int)
b=np.ones((4,5))
np.vstack((a,b))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [66]:
a=np.arange(0,12)
A=a.reshape(4,3)
At=A.transpose()
B=np.dot(A,At)
print(B)
np.shape(B)
#4/4
np.linalg.det(B)
#определитель равен нулю следовательно обратная матрица невозможна

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


0.0

In [67]:
np.random.seed(42)
A=np.random.randint(0,16,16)
C=A.reshape(4,4)
D=np.add(B,C*10)

In [68]:
np.linalg.det(D)

-28511999.999999944

In [69]:
np.linalg.matrix_rank(D)

4

In [70]:
D_inv=np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

In [71]:
#10 
for index, i in np.ndenumerate(D_inv):       
    if i<0:
        D_inv[index]=0
    elif i>0:
        D_inv[index]=1
D_inv


# Задание 2
# Создайте массив Numpy под названием a размером 5x2, 
# то есть состоящий из 5 строк и 2 столбцов.
# Первый столбец должен содержать числа 1, 2, 3, 3, 1, 
# а второй - числа 6, 8, 11, 10, 7.
# Будем считать, что каждый столбец - это признак, 
# а строка - наблюдение.
# Затем найдите среднее значение по каждому признаку, 
# используя метод mean массива Numpy.
# Результат запишите в массив mean_a, в нем должно быть 2 элемента.

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [72]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_b = np.mean(a[:,0])
mean_b
mean_c=np.mean(a[:,1])
mean_c
mean_a = np.stack((mean_b, mean_c))
mean_a


array([2. , 8.4])

In [73]:
#Задание 3
# Вычислите массив a_centered, отняв от значений массива а
# средние значения соответствующих признаков, содержащиеся в массиве mean_a.
# Вычисление должно производиться в одно действие.
# Получившийся массив должен иметь размер 5x2.

In [73]:

a_centred = np.column_stack((a[:,0]-mean_b, a[:,1]-mean_c ))
a_centred

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [74]:
#Задание 4
# Найдите скалярное произведение столбцов массива a_centered.
# В результате должна получиться величина a_centered_sp.
# Затем поделите a_centered_sp на N-1, где N - число наблюдений.

a_centered_sp = np.dot(a[:,0], a[:,1])
print (a_centered_sp)

92


In [75]:
arraysize = a_centered_sp/((np.size(a_centred))-1)
arraysize

10.222222222222221